# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Cricia Silverberg
title: Avid Learner
email: cricia.s@gmail.com
#website: www.github.com/danwong

# Social links
#twitter_username: facespics
github_username:  cricias
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cricia_silverberg
linkedin_username: cricia
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profilepic.JPG
about_content: | # this will include new lines to allow paragraphs
 Hi, my name's Cricia and I am a new graduate from San Jose State University. I am experienced in education and child psychology. :)
t
  [Here's my resume! :)](files/CriciaResume.pdf)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my interests and hobbies are:
   - Technology 
   - Weightlifting 
   - Food 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
